- bin/version-manager.js
With this change, the following syntaxes are now valid:
* `versioned-tests`: Will look for tests with the following globs:
* `test/versioned/**/package.json`
* `tests/versioned/**/package.json`
* `node_modules/**/tests/versioned/**/package.json` <-- For the agent to seamlessly work with the tests of deps!
* `versioned-tests test/versioned/hapi`: Will look with these globs:
* `test/versioned/hapi/package.json`
* `test/versioned/hapi/**/package.json`
* `versioned-tests test/versioned/mongodb/package.json`: Will look only at:
* `test/versioned/mongodb/package.json`
> Made versioned runner more flexible in file inputs

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/enhancement-request.md
- .github/PULL_REQUEST_TEMPLATE.md
* Added GitHub PR template
* Added GitHub issue templates
> GitHub templates

- bin/publish-docs.sh
- bin/version-manager.js
- index.js
- lib/agent.js
- lib/assert.js
- lib/util.js
- lib/versioned/matrix.js
- lib/versioned/packager.js
- lib/versioned/printers/index.js
- lib/versioned/printers/pretty.js
- lib/versioned/printers/printer.js
- lib/versioned/printers/simple.js
- lib/versioned/runner.js
- lib/versioned/suite.js
- lib/versioned/test.js
- tests/unit/agent.tap.js
- tests/unit/assert.tap.js
- tests/unit/index.tap.js
- tests/unit/newrelic.js
- tests/unit/util.tap.js
- tests/unit/versioned/matrix.tap.js
- tests/unit/versioned/mock-tests/other.mock.js
- tests/unit/versioned/mock-tests/redis.mock.js
- tests/unit/versioned/suite.tap.js
- tests/unit/versioned/test.tap.js
* Added copyright headers to all source files
> Added copyright headers to source files

- CONTRIBUTING.md
* Added contributing guidelines
> Added contributing guidelines files

- lib/versioned/runner.js
- lib/versioned/suite.js
- Tightened Up "Already Declared in Upper Scope" Lint Warnings
> Tightens Up "Already Declared in Upper Scope" Lint Warnings

- CHANGELOG.md
- CONTRIBUTING.md
* Updated to Apache 2.0 license.
* Bumped minimum dev dependency of newrelic (agent) to 6.11 for license matching.
* Updated metric retrieval from agent for `assert.metrics` to match newer agent versions.
**Breaking:** assertions are now only compatible with newrelic (agent) versions 6+.
* Added third party notices file and metadata for dependencies.
* Updated readme with more detail.
* Added issue templates for bugs and enhancements.
* Added code of conduct file.
* Added contributing guide.
* Added pull request template.
* Migrated CI to GitHub Actions.
* Added copyright headers to all source files.
* Added .vscode to .gitignore.
* Added additional items to .npmignore.
- https://github.com/newrelic/node-test-utilities/pull/45
- https://github.com/newrelic/node-test-utilities/pull/46
- …
> Release v4.0.0

- lib/agent.js
* Creates config instance via Config.createInstance() to pass to agent instead of using Config.initialize().
Previously, the agent and created segments could end up with different config instances resulting in config updates (such as attribute configuration) not propagating correctly for tests. Now, the agent uses the same initialized singleton similar to regular execution.
> Creates config instance to pass to agent

- CHANGELOG.md
- Creates config instance via Config.createInstance() to pass to agent instead of using Config.initialize().
Previously, the agent and created segments could end up with different config instances resulting in config updates (such as attribute configuration) not propagating correctly for tests. Now, the agent uses the same initialized singleton similar to regular execution.
> Release v4.1.2

- .github/workflows/ci-workflow.yml
* Added Node 14 to CI configuration.
> Adds Node 14 to CI configuration.

- .github/workflows/ci-workflow.yml
- package.json
> Remove Node v8.x from CI

- bin/version-manager.js
- lib/util.js
- lib/versioned/suite.js
- tests/unit/util.tap.js
> Use Sets, code cleanup

- .gitignore
- THIRD_PARTY_NOTICES.md
- package-lock.json
- package.json
- tests/unit/agent.tap.js
- tests/unit/assert.tap.js
- tests/unit/util.tap.js
- tests/unit/versioned/matrix.tap.js
- tests/unit/versioned/suite.tap.js
- tests/unit/versioned/test.tap.js
- third_party_manifest.json
* Upgraded tap to `^15.0.9`
* Updated third-party notices and manifest to reflect most recent deps
* Removed package-lock from .gitignore to keep in sync 
* Upgraded `sinon` to `^11.1.1` to remove remaining npm audit errors
> Upgrade tap

- lib/versioned/test.js
- tests/unit/versioned/test.tap.js
* Refactored test pattern filtering by extracting to its own function.  Also added a few missing test pattern test cases.
> Extracted test pattern filtering

- CHANGELOG.md
* Fix pattern matching regression when parsing names of test files.
* Refactored test pattern filtering by extracting to its own function. Also added a few missing test pattern test cases.
* https://github.com/newrelic/node-test-utilities/pull/97
* https://github.com/newrelic/node-test-utilities/pull/98
> Release v6.1.1

- THIRD_PARTY_NOTICES.md
- lib/agent.js
- package-lock.json
- package.json
- tests/unit/agent.tap.js
- third_party_manifest.json
* Added clearing of registered instrumentation to `unload`.
* Added `getContextManager` to retrieve the active context manager in agent versions 8.6.0+.
* Bumped `newrelic` dev dependency to `^8.6.0`.
This will enable cleaning up some test usages of `tracer` as well as do better cleanup for potential test scenarios.
> Updates to support recent agent changes

- CHANGELOG.md
* Added clearing of registered instrumentation to `unload`.
* Added `getContextManager` to retrieve the active context manager in agent versions 8.6.0+.
* Bumped `newrelic` dev dependency to `^8.6.0`.
* https://github.com/newrelic/node-test-utilities/pull/100
> Release 6.2.0

- bin/version-manager.js
- lib/versioned/printers/printer.js
- lib/versioned/test.js
- tests/unit/versioned/globber.tap.js
- tests/unit/versioned/mock-tests/other.mock.tap.js
- tests/unit/versioned/mock-tests/package.json
- tests/unit/versioned/mock-tests/redis.mock.tap.js
- tests/unit/versioned/printers/printer.tap.js
- tests/unit/versioned/suite.tap.js
- tests/unit/versioned/test.tap.js
- Warn or throw an error if tests present in testing directory are not included in test specification.
- Closes https://github.com/newrelic/node-test-utilities/issues/88
> warn if test files are not included in spec

- package-lock.json
* Resolved several dev-dependency audit warnings.
> Resolves several dev-only npm audit warnings.

- THIRD_PARTY_NOTICES.md
- package-lock.json
- package.json
- third_party_manifest.json
* Bumped `tap` to ^16.0.1.
* Various dev-dependency updates to `package.lock` via `npm audit fix`.
> Bump tap resolve warning

- .github/workflows/ci-workflow.yml
* Updated CI to run against Node versions 14-18.
> Updates CI to run on Node versions 14-18.

- package-lock.json
- package.json
- third_party_manifest.json
* Drops support for Node 12.
* Updates engines to Node >= 14.
* https://issues.newrelic.com/browse/NR-35637
> Drops Node 12.

- bin/version-manager.js
* Updated test runner to use max CPUs available to run test folders in parallel when the `--jobs` parameter is not specified.
Locally, saw a 30-40% speed improvement when doing a full versioned run of the main agent against a locally packed version of the test runner.
May increase the chance of test flickers due to port usage. Depends on how we've specified tests and safety built into any frameworks when using port 0. If I remember right, using 0 port through the underlying http module doesn't guarantee it grabs an unused port. As such, we may need to introduce some safety mechanisms if we start seeing non-deterministic tests. I believe there's a pattern around this in the helper in the main agent.
The GitHub runners have minimal resources so we may or may not see benefits there (or see …
> Uses max CPUs available by deafult to run test folders in parallel

- lib/versioned/runner.js
Signed-off-by: mrickard <maurice@mauricerickard.com>
* Added detection for node version < 18, to supply correct loader flag
https://issues.newrelic.com/browse/NEWRELIC-3566
> Version check before specifying loader flag

- .c8rc.json
- .github/workflows/ci-workflow.yml
- README.md
- THIRD_PARTY_NOTICES.md
- package-lock.json
- package.json
- third_party_manifest.json
https://app.codecov.io/gh/newrelic/node-test-utilities/tree/NR-60779-codecov
* Updated tests to use c8
* Added codecov upload to CI build
* Added badges 🙌🏻
> NR-60779 wire up c8 and codecov for coverage collection

- THIRD_PARTY_NOTICES.md
- lib/assert.js
- lib/util.js
- package-lock.json
- package.json
- tests/unit/assert.tap.js
- tests/unit/index.tap.js
- third_party_manifest.json
Signed-off-by: mrickard <maurice@mauricerickard.com>
Added `assertCLMAttrs` testing method to utils, so it can be used to test CLM behavior in external repos
https://issues.newrelic.com/browse/NEWRELIC-5779
> Added CLM helper to utils

- README.md
* Update README header image to latest OSS office required images
Closes NEWRELIC-7076
* New header image supports both light and dark mode, and repolinter complains about using the dark only image
> chore: update to newest community header

- .github/workflows/ci-workflow.yml
* Updated CI to run against versions 16-20.
Closes #175
> chore: added node 20 and drop node 14 in CI

- package.json
- third_party_manifest.json
* **BREAKING CHANGE**: Removed support for Node 14.
Closes #176
> chore!: dropped node 14

- .github/workflows/ci-workflow.yml
- package-lock.json
> chore: add missing data to lockfile

- .github/workflows/prepare-release.yml
> chore: Fixed typo in workflow variable

- THIRD_PARTY_NOTICES.md
- bin/update-third-party-notices.sh
- lib/agent.js
- package-lock.json
- package.json
- third_party_manifest.json
- **chore: Updated mock agent to exclusively rely on InstrumentationTracker**
- **chore: updated udpate-third-party-notices.sh to only update notices when dep changes occur**
Closes #199
> chore: Updated mock agent to exclusively rely on InstrumentationTracker

- .github/workflows/ci-workflow.yml
- lib/versioned/runner.js
- package.json
I did not target this against a `next` branch as we rarely fix this repo and its used internally. I also removed some check to pass `--experimental-loader` for < 18 and `--loader` for all.  They both work, and we'll have to eventually update this in future node versions when it turns into `--import` anyways.
Closes #215
> feat!: Dropped support for Node.js 16

- .github/workflows/ci-workflow.yml
- package.json
Removed node.js 18 since it's EOL'd.
> feat!: Removed Node.js 18 support
