lib/versioned/runner.js
Latest versions of npm always save added modules to the `package.json` which is annoying when running several installs back-to-back.
=> Do not save installed packages.

lib/versioned/runner.js
Timed-out tests have been terminating with `null` codes, so they are always diverted through the wrong branch before ultimately finishing with a [false positive](https://github.com/newrelic/node-test-utilities/blob/master/lib/versioned/runner.js#L39) (`err.code` is falsey, therefore it exits with `0`).
=> NODE-1656 fix(runner): account for null exit code

CHANGELOG.md, README.md
- Added `TestAgent` helper class.
This class provides simple to use helpers for running your tests with the agent
and in transactions.
- Added `tap` assertions.
If your tests use [`tap`](https://www.npmjs.com/package/tap), then you can add
some helpful assertions to your tests using this module.
- Added version matrix test running.
This is a script for executing your instrumentation's tests against many
versions of the module you are instrumenting.
=> Updated changelog for v1.0.0

lib/agent.js, lib/assert.js, lib/util.js, tests/unit/agent.tap.js, tests/unit/util.tap.js
Added check for `AGENT_PATH` environment variable.
This environment variable can be used to specify the location of the `newrelic` package that these test utilities will load. It should be the path to the root directory of the agent. If the environment variable is not set, then the `newrelic` module that was installed (e.g. is in a `node_modules` directory) is used instead.
=> NODE-1703 Added hook for specifying newrelic path.

bin/version-manager.js, lib/versioned/printers/printer.js, lib/versioned/printers/simple.js, lib/versioned/test.js
Versioned tests are now named better when they are coming from the `versioned` directory directly. In that case, the name from the package.json is used instead.
=> Fixed test naming

lib/agent.js, lib/assert.js, tests/unit/assert.tap.js
This change allows people to use `t.transaction(tx)` and still have a meaningful message.
=> Added default messages to asserts

.travis.yml, package.json, tests/unit/versioned/test.tap.js
These versions of Node are no longer supported by the agent, so they are being dropped by the test library.
=> Dropping support for 0.10 and 0.12

.eslintrc, bin/version-manager.js, index.js, lib/agent.js, lib/util.js, lib/versioned/suite.js, tests/unit/util.tap.js
* Added `isLocalhost` and `getDelocalizedHostname` to utilities methods.
These methods are useful for determining the host name as the New Relic agent sees it. When making metrics and event attributes, the delocalized hostname is what the agent will use.
=> Added `isLocalhost` and `getDelocalizedHostname`

CHANGELOG.md
- Dropped support for Node 0.10 and Node 0.12.
- Added `isLocalhost` and `getDelocalizedHostname` to utilities methods.
These methods are useful for determining the host name as the New Relic agent
sees it. When making metrics and event attributes, the delocalized hostname is
what the agent will use.
=> Updated changelog for v2.0.0

.gitignore, bin/version-manager.js
Adds ability to skip tests/files by including a `-skip` or `--skip` option.
The following would run all found versioned tests *except* the koa ones. 
`versioned-tests --skip koa`
Long-term, should probably let this accept a single keyword or a collection.
=> Adds ability to skip files/tests based on including a keyword.

package.json
* **BREAKING** Removed support for Node 6, 7, and 9.
The minimum supported version is now Node v8. For further information on our support policy, see: https://docs.newrelic.com/docs/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent.
=> updated engines field to at least v8

lib/versioned/matrix.js
allows for limiting the number of versions being run against per dependency in the dependencies object.
an example configuration would be as such:
```
{
"name": "aws-sdk-tests",
"version": "0.0.0",
"private": true,
"tests": [
{
"engines": {
"node": ">=8.0"
},
"dependencies": {
"aws-sdk": {
"versions": ">=2.380.0",
"samples": 10
}
},
"files": [
"aws-sdk.tap.js",
"dynamodb.tap.js",
"http-services.tap.js",
"s3.tap.js"
]
}
],
"dependencies": {}
}
```
=> added a samples flag to deps to allow for version limiting

lib/agent.js, tests/unit/agent.tap.js
* Added `TestAgent.getAgentApi()` function that returns an agent API instance for the underlying agent instance.
So-far, external instrumentation has bypassed the API and used this to go straight to the shimmer. The current style of instrumentation we are working on will not be gated on module load (at least at first), so it needs to go through the proper channel of the API.
This will return a cached API instance for the underlying agent.
This also includes some small const/let code style changes, since I was in there and the test file was small. Those changes are in a separate commit to make review easier.
=> Add getAgentApi helper

lib/assert.js, tests/unit/assert.tap.js
* Added better handling of soft-matching segments for cases where siblings have duplicate names.
This is sort of a quick/naive fix that will search one more level when multiple siblings are found with the same matching name. A common example would be `middleware: <anonymous>`.  This solution will grab the first child that has a grandchild that also matches the next level.
A better long-term fix would add depth search but it would require a larger overhaul of the logic and may not get to the level of need. The expectedSegments tends to be used more but for my use case, I didn't want to account for every possible segment by frameworks in play.
=> Adds handling of duplicate sibling names when searching for children.

CHANGELOG.md, THIRD_PARTY_NOTICES.md, third_party_manifest.json
- Added Node v14.x to CI.
- Removed Node v8.x from CI.
- Updates to README to match New Relic OSS template.
https://github.com/newrelic/node-test-utilities/pull/68
https://github.com/newrelic/node-test-utilities/pull/69
https://github.com/newrelic/node-test-utilities/pull/71
=> Release v5.0.0

bin/version-manager.js, lib/versioned/matrix.js, lib/versioned/printers/printer.js, tests/unit/versioned/matrix.tap.js
* Enumerates versions of every module being tested
Do I need to create a ticket for this?
Here's an example output from `node-newrelic`
```sh
@koa/router: 8.0.8, 9.4.0, 10.0.0
koa: 0.21.1, 1.7.0, 2.13.1
koa-route: 1.1.4, 2.4.2, 3.2.0
aws-sdk: 1.18.0, 2.899.0
koa-router: 1.6.1, 2.4.4, 3.8.0, 4.3.2, 5.4.2, 6.2.0, 7.4.0, 8.0.8, 9.4.0, 10.0.0
amazon-dax-client: 1.2.5
amqplib: 0.7.1
bluebird: 0.11.6, 1.2.4, 2.11.0, 3.7.2
continuation-local-storage: 0.1.1, 1.1.1, 2.6.2, 3.2.1
connect: 0.5.10, 1.9.2, 2.30.2, 3.7.0
director: 1.2.8
express: 0.14.1, 1.0.8, 2.5.11, 3.21.2, 4.17.1
superagent: 0.21.0, 1.8.5, 2.3.0, 3.8.3, 4.1.0, 5.3.1, 6.1.0
express-enrouten: 0.3.0, 1.3.0
cassandra-driver: 1.0.3, 2.2.2, 3.6.0, 4.6.2
ejs: 0.8.8, 1.0.0, 2.7.4, 3.1.6
generic-pool: 1.0.12, 2.5.4, 3.7.8
fastify: 0.43.0, …
```
=> includes _every_ version the tests are being run on for transparency

.github/workflows/ci-workflow.yml, package.json, tests/unit/versioned/test.tap.js
PR for Node 16 support research
* Added Node.js 16 CI support
* Loosened assertions to make integration tests pass on both npm v6 and v7
=> adding node 16 in version matrix, and see what breaks

CHANGELOG.md
* Added the `-P, --pattern` flag to allow filtering tests by keyword(s).
* Added support for running specific test files by name or globbing pattern.
* Added a `--samples` value to CLI to allow an override of sampling for a given test run.
Global sample value will be used when it is less than the samples value set on a given package in the tests stanza.
* Added ability to run versioned tests against version tags. For example: `newrelic@latest`.
When a version such as `package@latest` is specified in the versioned test `package.json` declarations, it won't directly satisfy semver matches against the package versions manually pulled down and cached. The runner now attempts to directly install the configured version, which also results in a test failure if the package fails to install. …
=> Release v6.1.0.

lib/agent.js, tests/unit/agent.tap.js
* Added `getShim` method for retrieving a test Shim instance.
This enables test setup involving instrumentation like scenarios (adding segments, etc.) without reaching into the internal tracer.
Helps enable removing all usages of tracer from external module test code. Debated adding a method to the helper to abstract the need but went with shim creation since the shim is a public instrumentation API (breaking changes are semver major) and having more examples even in test code seems helpful.
=> Adds getter for a test shim instance

lib/versioned/matrix.js, lib/versioned/printers/printer.js, tests/unit/versioned/matrix.tap.js, tests/unit/versioned/printers/printer.tap.js
* Added printing list of packages and their versions at the end of a run.
Based on an old PR I opened #89, I think I meant to add this but never did.  I noticed we have an issue with package resolution when the range specified does not match the latest version in a package for a given semver major range.  I plan on following up with a fix for that.  Here is the output
```sh
✓ mysql2 (4) 20s
✓ pg-post-7 (1) 10s
pg-pre-7
✓ redis (2) 5s
✓ restify-post-7 (14) 35s
✓ restify-pre-7 (12) 30s
✓ superagent-tests (12) 24s
✓ undici (1) 6s
✓ v2 (9) 38s
✓ v3 (13) 1m
===============================================================
Versions executed
aws-sdk(2): 2.2.48, 2.1092.0
amazon-dax-client(1): 1.2.7
@aws-sdk/client-api-gateway(1): 3.54.0
@aws-sdk/client-elasticache(1): 3.54.0 …
```
=> added printing versioned matrix by pkg at the end of test run before the missing tests message

lib/util.js, tests/unit/util.tap.js
* Sort package versions properly when returning max version by every semver range.
This was causing issues in apollo-server versioned tests and I realized the last element in the version array was not always the "latest".  This PR will sort float strings ascending to ensure the last element is latest.
=> sort versions when finding max version by semver range

THIRD_PARTY_NOTICES.md, lib/versioned/suite.js, package-lock.json, package.json, third_party_manifest.json
* Bumped async to ^3.2.3.
Updated usage of `queue.drain` which was a 3.x breaking change.
There's some concurrent functionality of async used in suite.js that would make removing async take a bit longer than ideal, so upgrading for now.
https://github.com/caolan/async/blob/master/CHANGELOG.md#v300
=> Bumps async to ^3.2.3.

lib/versioned/runner.js
* Updated version runner to fail if package fails to install and not attempt to clean the npm cache.
Closes #129
I didn't update any tests because we don't explicitly test the runner as it is very hard.  To test I did the following
```
npm link
```
In agent
```
npm link @newrelic/test-utilities
npm run versioned
```
=> Remove cleaning npm cache on package install failure

README.md, lib/versioned/runner.js
* Add TEST_CHILD_TIMEOUT environment variable to modify test timeout limits.
* Closes https://github.com/newrelic/node-test-utilities/issues/132
Includes no tests, only a readme update, because nothing tests the runner apparently. I've tested it manually and it works fine.
=> add TEST_CHILD_TIMEOUT for modifying test timeouts

THIRD_PARTY_NOTICES.md, lib/assert.js, package-lock.json, package.json, tests/unit/assert.tap.js, tests/unit/util.tap.js, third_party_manifest.json
Signed-off-by: mrickard <maurice@mauricerickard.com>
Streamlined CLM assertions to inherit tap from context. 
Bypassed tapper/asserter abstractions so that CLM test failures are exposed.
https://issues.newrelic.com/browse/NEWRELIC-5779
=> Streamlined CLM assertion tests, bypassing old abstractions

THIRD_PARTY_NOTICES.md, lib/agent.js, package-lock.json, package.json, tests/unit/agent.tap.js, third_party_manifest.json
* Provided ability to register only core instrumentation or both core and 3rd party instrumentation.  `TestAgent.makeFullyInstrumented` will register both.  `TestAgent.makeInstrumented` will only register core instrumentation.
Note: This needs https://github.com/newrelic/node-newrelic/pull/1559 that has new methods to register core and 3rd party instrumentation.  Now that we will support registering hooks for the same module we need to skip registering 3rd party for our external modules since we want to only load its local instrumentation in case we have made changes.  If we just register it now it adds additional instrumentation making some tests to fail but also makes it a bad test.
=> Provide ability to register core and 3rd party instrumentation

.eslintrc.js, THIRD_PARTY_NOTICES.md, lib/agent.js, package-lock.json, package.json, tests/unit/agent.tap.js, third_party_manifest.json
* Updated `TestAgent.getShim` to require an exported module and pull the shim symbol.
Closes #165
This is necessary as you need to get the specific shim instance for an exported module now now just any shim instance.  This is because `shim.isWrapped` makes sure your shim.id mathces.
=> updated getShim to look for shim symbol on exported module

THIRD_PARTY_NOTICES.md, lib/versioned/runner.js, lib/versioned/test.js, package-lock.json, package.json, tests/unit/versioned/test.tap.js, third_party_manifest.json
* gate usage of loader in versioned tests by NR_LOADER environment variable
Instead of completely removing the loader functionality for node 20, we're gating it off of the NR_LOADER environment variable, which was already part of the logic. This will make it easier on us when we re-add the ESM loader at a later date. Additionally bumped some deps to fix `npm audit` warnings.
=> refactor: gate usage of loader in versioned tests by NR_LOADER environment variable

THIRD_PARTY_NOTICES.md, lib/agent.js, package-lock.json, package.json, tests/unit/agent.tap.js, third_party_manifest.json
* Updated the TestAgent to call `shimmer.registerHooks` and `shimmer.removeHooks` to set up instrumentation and remove it.
This assumes the work in https://github.com/newrelic/node-newrelic/pull/1758 is merged and released.  
This change isn't necessary until after release of the agent because I kept those functions.  Technically `shimmer.registerHooks` should now be called after bootstrapping instrumentation but it's ok for now.
=> chore: updated fake agent to register ritm hooks

lib/bedrock-server/responses/amazon.js
+ Added a new Amazon Titan LLM responses to support `token_count` work.
We need this to support https://github.com/newrelic/node-newrelic-aws-sdk/issues/263.
=> chore: Added response for testing llm.token_count

THIRD_PARTY_NOTICES.md, lib/agent.js, package-lock.json, package.json, third_party_manifest.json
This PR updates the minimum version of `newrelic` in order to utilize the instrumentation tracker instead of `Object.create(null)` in the agent helper.
=> chore: Added instrumentation tracking to support newrelic issue 2033

bin/version-manager.js, lib/versioned/printers/index.js, lib/versioned/printers/quiet.js
This is in service to https://github.com/newrelic/node-newrelic/issues/2122.
I have tested this locally by `npm link`ing this into my local `newrelic` repo, modifying tests to fail, and running the versioned tests. When there are test failures, output is printed to screen. When tests are successful, nothing is printed.
=> feat: Added a quiet mode printer to versioned-tests

package.json, tests/unit/versioned/globber.tap.js, tests/unit/versioned/mock-esm-tests/package.json, tests/unit/versioned/mock-esm-tests/redis.mock.test.js, tests/unit/versioned/mock-tests/other.mock.test.js, tests/unit/versioned/mock-tests/package.json, tests/unit/versioned/mock-tests/redis.mock.test.js, tests/unit/versioned/printers/printer.tap.js, tests/unit/versioned/suite.tap.js, tests/unit/versioned/test.tap.js
fixed printers test as it was not being run,
Amy noticed this when she was working on her refactor.  This PR fixes the regex for tap to make sure all unit tests were being run. I had to rename to fake tests from `.tap.js` to `test.js` so they wouldn't get run.
=> ci: Fixed test script to run all unit tests

bin/version-manager.js, lib/versioned/packager.js, lib/versioned/runner.js, lib/versioned/suite.js, tests/unit/versioned/suite.tap.js
- Got rid of async functions in runner
- Got rid of async.waterfall in Suite.start()
- Reduced complexity of async.queue and async.mapLimit in Suite._runTests() and Suite._mapPackagesToVersions(), respectively
- Removed unnecessary callbacks and a test that checks for a callback
=> refactor: Reduced dependency on async library

bin/version-manager.js, lib/versioned/suite.js, tests/unit/versioned/suite.tap.js
Removes the install queue as it was adding unneccessary complexity.  Now the code will install packages if it needs to and then execute a given test suite when install is done. Before it did the same but queued up installs separately so it was doing a lot of waiting.
```
npm test
```
To test with agent
```
npm link
npm link @newrelic/test-utilities
npm run versioned:internal:major
```
Closes #220
=> refactor: Removed install queue from versioned runner. It will install before running a given test and rely on the jobs limit

bin/version-manager.js, lib/versioned/suite.js
This PR adds a new option to the versioned tests runner that enables calculating the number of tests that will be run and printing only that information.
<details>
<summary>Example output</summary>
```sh
@prisma/client(19)
prisma(104)
Module Test Versions Counts
@apollo/gateway                        6
@apollo/server                         12
@apollo/subgraph                       15
@aws-sdk/client-api-gateway            322
@aws-sdk/client-bedrock-runtime        68
@aws-sdk/client-dynamodb               337
@aws-sdk/client-elastic-load-balancing 318
@aws-sdk/client-elasticache            325
@aws-sdk/client-lambda                 337
@aws-sdk/client-rds                    364
@aws-sdk/client-redshift               326
@aws-sdk/client-rekognition            325
@aws-sdk/client-s3 …
```
=> feat: Added a --matrix-count parameter to versioned tests
